service: gitmeet-api-projects

useDotenv: true

provider:
  name: google
  labels:
    application: gitmeet-projects-api
  stage: dev
  runtime: nodejs12
  region: asia-south1
  project: shark-hacks-297613
  credentials: ~/.gcloud/sharkhackskeyfile.json

frameworkVersion: "2"

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  createSchema:
    handler: createSchema
    events:
      - http: path
        path: projects
        method: post
