service: gitmeet-api-projects

useDotenv: true

provider:
  name: google
  labels:
    application: gitmeet-projects-api
  stage: dev
  runtime: nodejs12
  region: asia-south1
  project: shark-hacks-297613
  credentials: ~/.gcloud/sharkhackskeyfile.json

frameworkVersion: "2"

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  createSchema:
    handler: createSchema
    events:
      - http: path
        path: projects
        method: post
  createProject:
    handler: createProject
    events:
      - http: path
        path: projects
        method: post
  getProject:
    handler: getProject
    events:
      - http: path
        path: projects
        method: post
  deleteProject:
    handler: deleteProject
    events:
      - http: path
        path: projects
        method: post
  editProject:
    handler: editProject
    events:
      - http: path
        path: projects
        method: post
  swipeProject:
    handler: swipeProject
    events:
      - http: path
        path: projects
        method: post
