service: gitmeet-api-users

useDotenv: true

provider:
  name: google
  labels:
    application: gitmeet-users-api
  stage: dev
  runtime: nodejs12
  region: asia-south1
  project: shark-hacks
  credentials: ~/.gcloud/keyfile-shark-hacks.json

frameworkVersion: "2"

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  create:
    handler: create
    events:
      - http: path
        path: users
        method: post

  all:
    handler: all
    events:
      - http: path
        path: users
        method: get

  single:
    handler: single
    events:
      - http: path
        path: users
        method: get
