service: gitmeet-api-users

useDotenv: true

provider:
  name: google
  labels:
    application: gitmeet-users-api
  stage: dev
  runtime: nodejs12
  region: asia-south1
  project: shark-hacks-297613
  credentials: ~/.gcloud/sharkhackskeyfile.json

frameworkVersion: "2"

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  createSchema:
    handler: createSchema
    events:
      - http: path
        path: users
        method: post

  createUser:
    handler: createUser
    events:
      - http: path
        path: users
        method: post

  getUser:
    handler: getUser
    events:
      - http: path
        path: users
        method: get
  
  auth:
    handler: auth
    events:
      - http: path
        path: users
        method: get
  
  callback:
    handler: callback
    events:
      - http: path
        path: users
        method: get
  
  editUser:
    handler: editUser
    events:
      - http: path
        path: users
        method: get

  verfiyUser:
    handler: verfiyUser
    events:
      - http: path
        path: users
        method: get
